services:
  cognity:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cognity-app

    depends_on:
      - postgres

    environment:
      MASTRA_STORAGE_PATH: /app/.mastra/mastra.db
    
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      LOCAL_OLLAMA_URL: http://host.docker.internal:11434/v1
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/cogassy

      TELEGRAM_POLL_TIMEOUT_SECONDS: ${TELEGRAM_POLL_TIMEOUT_SECONDS:-30}
      TELEGRAM_RETRY_DELAY_MS: ${TELEGRAM_RETRY_DELAY_MS:-1500}
      TELEGRAM_POLL_START_OFFSET: ${TELEGRAM_POLL_START_OFFSET:-0}
      BASE_CURRENCY: ${BASE_CURRENCY:-DOP}
      EXCHANGE_RATE_API: ${EXCHANGE_RATE_API:-https://v6.exchangerate-api.com/v6}
      EXCHANGE_RATE_API_KEY: ${EXCHANGE_RATE_API_KEY}

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./mastra-data:/app/.mastra
      
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: cognity-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cogassy

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres-data: